codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 75%
        threshold: 1%
        if_ci_failed: error

    patch:
      default:
        target: 80%
        threshold: 5%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

ignore:
  - "tests/**/*"
  - "vendor/**/*"
  - "coverage-html/**/*"
  - "coverage-xml/**/*"
  - "scripts/**/*"
  - "*.php" # Root level test files
  - "NCAC/Sniffs/sniff-psalm-tokens.php" # Dev tool, not production code
