#!/bin/bash -e

# Environment Setup Script for NCAC PHPCS Standard Dev Container
# 
# This script generates a .env file with environment variables needed for development.
# 
# IMPORTANT: This script MUST be run on the WSL2 host BEFORE starting the Dev Container,
# because it needs to detect the WSL2 IP address for XDebug configuration.
#
# Usage:
#   1. Clone the repository in WSL2
#   2. Run this script: .docker/generate-env.sh
#   3. Start the Dev Container in VS Code
#
# The generated .env file will be used by docker-compose.yml for proper XDebug setup.

set -e  # Exit on any error

# Change to the script's directory to ensure relative paths work correctly
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_ROOT"

echo "🔧 Generating .env file for Dev Container..."
echo "📁 Working from project root: $(pwd)"

# Define the .env file path (relative to project root)
ENV_FILE=".env"

# Remove existing .env file if it exists
if [ -f "$ENV_FILE" ]; then
    echo "📝 Removing existing .env file..."
    rm -f "$ENV_FILE"
fi

# Detect WSL2 IP address for XDebug
echo "🔍 Detecting WSL2 IP address..."
WSL_IP=$(ip route | grep default | awk '{print $3}')

# Validate that we got an IP address
if [ -z "$WSL_IP" ]; then
    echo "❌ Error: Could not detect WSL2 IP address"
    echo "   This script must be run inside WSL2 environment"
    echo "   Make sure you're running this from WSL2, not from within a container"
    exit 1
fi

# Validate IP format (basic check)
if ! echo "$WSL_IP" | grep -E '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$' > /dev/null; then
    echo "❌ Error: Invalid IP address format: $WSL_IP"
    exit 1
fi

echo "✅ Detected WSL2 IP: $WSL_IP"

# Generate .env file
echo "📝 Writing environment variables to $ENV_FILE..."

cat > "$ENV_FILE" << EOF
# Environment variables for NCAC PHPCS Standard Dev Container
# Generated automatically by .docker/generate-env.sh
# Do not edit this file manually - it will be overwritten

# Application configuration
APP_NAME=ncac-phpcs-standard
PHP_VERSION=7.4.33
APP_ROOT=/workspace

# WSL2 and XDebug configuration
WSL_IP=$WSL_IP
XDEBUG_PORT=9047

# Generation timestamp
GENERATED_AT=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
EOF

echo "✅ Environment file generated successfully!"
echo ""
echo "📋 Generated variables:"
echo "   APP_NAME: ncac-phpcs-standard"
echo "   PHP_VERSION: 7.4.33"
echo "   APP_ROOT: /workspace"
echo "   WSL_IP: $WSL_IP"
echo "   XDEBUG_PORT: 9047"
echo ""
echo "🚀 You can now start the Dev Container in VS Code"
echo "   The .env file will be automatically loaded by docker-compose.yml"
